# A Pipeline defines a list of Tasks to execute in order, while
# also indicating if any outputs should be used as inputs of a following Task by
# using the from field and also indicating
# the order of executing (using the runAfter and from fields).
# The same variable substitution you used in Tasks is also available in a Pipeline.

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: myapp-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: myapp-image
      type: image
  tasks:
    - name: build-myapp
      taskRef:
        name: build-docker-image-from-git-source
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/docker-source/simpleapp 
      resources:
        inputs:
          - name: docker-source
            resource: source-repo
        outputs:
          - name: builtImage
            resource: myapp-image
    - name: deploy-myapp
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: myapp-image
            from:
              - build-myapp
      params:
        - name: path
          value: /workspace/source/simpleapp/DeployMyappToKube.yaml 
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
