apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: phx.ocir.io/axe8cdkpdr85/tekton-example/myapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "myapp-service"
  namespace: "default"
  labels:
    app: "myapp"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "myapp"
  type: "LoadBalancer"
  loadBalancerIP: ""