apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - secretName: tls-secret
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: myapp-service # REPLACE WITH YOUR SERVICE NAME FROM STEP 2
              servicePort: 80
